# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -2.792526
    max_position: 2.792526
    has_velocity_limits: true
    max_velocity: 2.443460
    has_acceleration_limits: true
    max_acceleration: 0.039951
  joint2:
    has_position_limits: true
    min_position: -1.047197
    max_position: 1.396263
    has_velocity_limits: true
    max_velocity: 2.356194
    has_acceleration_limits: true
    max_acceleration: 2.705526
  joint3:
    has_position_limits: true
    min_position: -1.308996
    max_position: 1.658062
    has_velocity_limits: true
    max_velocity: 2.356194
    has_acceleration_limits: true
    max_acceleration: 0.306514
  joint4:
    has_position_limits: true
    min_position: -3.665191
    max_position: 3.665191
    has_velocity_limits: true
    max_velocity: 1.685988
    has_acceleration_limits: true
    max_acceleration: 2.103745
  joint5:
    has_position_limits: true
    min_position: -2.094395
    max_position: 2.094395
    has_velocity_limits: true
    max_velocity: 3.490659
    has_acceleration_limits: true
    max_acceleration: 1.621505
  joint6:
    has_position_limits: true
    min_position: -6.283185
    max_position: 6.283185
    has_velocity_limits: true
    max_velocity: 5.235988
    has_acceleration_limits: true
    max_acceleration: 2.199115
