controller_names:
  - khi_upper_arm_controller
  - khi_lower_arm_controller

khi_upper_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - upper_joint1
    - upper_joint2
    - upper_joint3
    - upper_joint4

khi_lower_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - lower_joint1
    - lower_joint2
    - lower_joint3
    - lower_joint4
